article like and follow func/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

article like and follow func/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

article like and follow func/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

article like and follow func/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name="followers")

article like and follow func/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

article like and follow func/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):

    # password = None

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)

article like and follow func/accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    AuthenticationForm, 
    PasswordChangeForm,
)
from django.views.decorators.http import require_http_methods, require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('articles:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            # user = form.save()
            # update_session_auth_hash(request, user)
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    # 로그인한 유저만 팔로우를 할 수 있다.
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        # 본인은 자기 자신을 팔로우 할 수 없다.
        if user != person:
            if person.followers.filter(pk=user.pk).exists():
                person.followers.remove(user)
            else:
                person.followers.add(user)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

article like and follow func/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class=container>
  <h1>비밀번호 변경</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="d-flex justify-content-between">
    <input type="submit" class="btn btn-primary">
  </form>
  <a href="javascript:history.back();" class="btn btn-secondary">BACK</a>
  </div>
</div>
{% endblock content %}

article like and follow func/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class=container>
  <h1>로그인</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="d-flex justify-content-between">
    <input type="submit" class="btn btn-primary">
  </form>
  <a href="javascript:history.back();" class="btn btn-secondary">BACK</a>
  </div>
</div>
{% endblock content %}

article like and follow func/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container d-flex justify-content-between mt-3">
  {% with followers=person.followers.all followings=person.followings.all %}
  <div class="d-flex">
    <h1>{{ person.username }}</h1>
    {% if user != person %}
    <form action="{% url 'accounts:follow' person.pk %}" method="POST">
      {% csrf_token %}
      {% if user in followers %}
        <button type="button" class="btn btn-light mx-2 mt-1" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          Following
        </button>
        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-body">
                Unfollow {{ person.username }} ?
              </div>
              <div class="modal-footer">
                <button type="btn" class="btn btn-secondary" data-bs-dismiss="modal">Cancle</button>
                <button type="btn" class="btn btn-primary">Unfollow</button>
              </div>
            </div>
          </div>
        </div>
      {% else %}
        <input type="submit" value="Follow" class="btn btn-primary mx-2 mt-1">
      {% endif %}
    </form>
    {% endif %}
    {% if user == person %}
      <a href="{% url 'articles:create' %}" class="mt-2 mx-3 text-muted">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
        </svg>
      </a>
    {% endif %}
  </div>  
    <div class="d-flex justify-content-end">
      <div style="display:inline;" class="text-center mx-4">{{ person.article_set.all|length }}<br>
        Posts
      </div>
      <div style="display:inline;" class="text-center mx-2">{{ followers|length }} <br>
        Followers
      </div>
      <div style="display:inline" class="text-center mx-2">{{ followings|length }} <br>
        Following
      </div>
    </div>
  {% endwith %}
</div>

<hr>

<div class="container">
  {% for article in person.article_set.all %}
    <a href="{% url 'articles:detail' article.pk %}" style="text-decoration:none">
      <div class="card mb-3" style="width:auto;">
        <div class="card-header">
          <h3 class="text-muted">{{ article.user }}</h3>
        </div>
        <div class="card-body">
          <h4 class="card-title text-black">{{ article.title }}</h4>
          <p class="card-text text-black">{{ article.content }}</p>
        </div>
          <div>
            <form action="{% url 'articles:likes' article.pk %}?next=/accounts/{{person.username}}" method="POST">
              {% csrf_token %}
              {% if user in article.like_users.all %}
                <div class="d-flex justify-content-start align-items-center">
                  <button class="btn" sytle="background-color: transparent;">
                    <i class="fa-solid fa-heart" style="color:red;"></i>
                  </button>
                  <p class="my-auto text-black">{{ article.like_users.all | length }} likes</p>
                </div>
      
              {% else %}
              <div class="d-flex justify-content-start align-items-center">
                <button class="btn" sytle="opacity:0; padding:0;">
                  <i class="fa-regular fa-heart" ></i>
                </button>
                {% if article.like_users.all %}
                  <p class="my-auto text-black" >{{ article.like_users.all | length }} likes</p>  
                {% endif %}
              </div>
              {% endif %} 
              
            </form>
          </div>
      </div>
    </a>
    {% endfor %}
</div>
  


{% endblock content %}

article like and follow func/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class=container>
  <h1>회원가입</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="d-flex justify-content-between">
    <input type="submit" class="btn btn-primary">
  </form>
  <a href="javascript:history.back();" class="btn btn-secondary">BACK</a>
  </div>
</div>
{% endblock content %}

article like and follow func/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class=container>
  <h1>회원정보 수정</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="d-flex justify-content-between">
    <input type="submit" class="btn btn-primary">
  </form>
  <a href="javascript:history.back();" class="btn btn-secondary">BACK</a>
  </div>
</div>
{% endblock content %}