0415pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

0415pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

0415pjt/pjt07/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

0415pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

0415pjt/movies/models.py
import django
from django.db import models
from django.conf import settings

# Create your models here.

class Movie(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    description = models.TextField()

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content

0415pjt/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta) :
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name')

0415pjt/movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.ModelForm):
    class Meta :
        model = Movie
        exclude = ("user",)


class CommentForm(forms.ModelForm):
    class Meta :
        model = Comment
        fields = ("content",)

0415pjt/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
# Create your views here.

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm
    context ={
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('movies:index')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/update.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('movies:index')


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

0415pjt/movies/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required


# Create your views here.
@require_safe
def index(request) :
    movies = Movie.objects.order_by('-pk')
    context = {
        'movies' : movies,
    }
    return render(request, 'movies/index.html',context)

@login_required
@require_http_methods(['GET','POST'])
def create(request) :
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie.save()
            return redirect('movies:detail', movie.pk)
    else :
        form = MovieForm()
    context = {
        'form' : form,
    }
    return render(request, 'movies/create.html',context)


@require_safe
def detail(request,pk):
    movie = get_object_or_404(Movie, pk=pk)
    comment_form = CommentForm()

    comments = movie.comment_set.all()
    context = {
        'movie' : movie,
        'comments' : comments,
        'comment_form' : comment_form,
    }
    return render(request, 'movies/detail.html', context)


@login_required
@require_http_methods(['GET','POST'])
def update(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    if request.user == movie.user:
        if request.method == 'POST':
            form = MovieForm(request.POST, instance=movie)
            if form.is_valid():
                movie = form.save()
                return redirect('movies:detail', movie.pk)
        else :
            form = MovieForm(instance=movie)
    else :
        return redirect('movies:index')
    context={
        'form':form,
        'movie':movie,
    }
    return render(request, 'movies/update.html', context)


@require_POST
def delete(request, pk):
    if request.user.is_authenticated :
        movie = get_object_or_404(Movie,pk=pk)
        if movie.user == request.user :
            movie.delete()
    return redirect('movies:index')


@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated :
        movie = get_object_or_404(Movie, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
        return redirect('movies:detail', movie.pk)
    return redirect('accounts:login')

@require_POST
def comments_delete(request, movie_pk, comment_pk):
    if request.user.is_authenticated :
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user :
            comment.delete()
    return redirect('movies:detail', movie_pk)

0415pjt/movies/templates/movies/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<h1>CREATE</h1>
<hr>

<form action='{% url 'movies:create' %}' method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary" value="SUBMIT">
</form>

<hr>
<a href='{% url 'movies:index' %}' class="btn btn-secondary">BACK</a>
  
{% endblock content %}

0415pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<h1>DETAIL</h1>
<hr>

<h4>{{ movie.title }}</h4>
<br>
<p>{{ movie.description }} </p>
<div class="d-flex justify-content-between">
  <div class="d-flex">
  <a href='{% url 'movies:update' movie.pk %}' class="btn btn-success mx-2 my-2">UPDATE</a>
  <form action='{% url 'movies:delete' movie.pk %}' method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE" class="btn btn-primary mx-2 my-2">
  </form>
</div>
<a href='{% url 'movies:index' %}' class="btn btn-secondary mx-2 my-2">BACK</a>
</div>
<hr>

<h6>댓글 목록</h6>

  <ul>
    {% for comment in comments %}
    <div class="d-flex justify-content-between">
      <li>{{ comment }}</li>
      {% if request.user == comment.user %}
          <form action="{% url 'movies:comments_delete' movie.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="DELETE">
          </form>
        {% endif %}
      </li>
    </div>
    {% endfor %}
  </ul>
  <hr>


  {% if request.user.is_authenticated %}
    <form action="{% url 'movies:comments_create' movie.pk %}" method="POST" class="d-inline">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <input type="submit" >
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}" ></a>
  {% endif %}

  {% endblock content %}

0415pjt/movies/templates/movies/index.html
{% extends 'base.html' %}


{% block content %}
  <div class="d-flex justify-content-between align-items-center">
  <h1>INDEX</h1>

  <a href="{% url 'movies:create' %}" class="btn btn-primary">CREATE</a>
  </div>
  <hr>
  <hr>
  {% for movie in movies %}
    <a href={% url 'movies:detail' movie.pk %}>
      <h3> {{ movie.title }} </h3>
    </a>
    <p>{{ movie.description }} </p>
    <hr>

  {% endfor %}

{% endblock content %}

0415pjt/movies/templates/movies/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

  <h1>UPDATE</h1>
  <hr>
  <form action='{% url 'movies:update' movie.pk %}' method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="reset" class="btn btn-warning mx-2 my-2" value="RESET">
    <input type="submit" class="btn btn-primary mx-2 my-2" value="SUBMIT">
  </form>
  <hr>
  <a href="movies:index" class="btn btn-secondary mx-2">BACK</a>
{% endblock content %}

0415pjt/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% if request.user.is_authenticated %}
      <div class="d-flex justify-content-between align-items-center my-2">
        <h1>Hello, {{ user }}</h1>
        <div class='d-flex justify-content-between align-items-center'>
          <form action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <input type="submit" class="btn btn-warning" value = "LOGOUT">
          </form>
          <a href="{% url 'accounts:update' %}" class="btn btn-info mx-2 my-2">MODIFY</a>
          <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-dark" value="WITHDRAWAL">
          </form>
        </div>
      </div>
      <hr><hr>
    {% else %}
    <hr>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary my-2 mx-2">LOGIN</a>
    <a href="{% url 'accounts:signup' %}" class="btn btn-success my-2 mx-2">SIGN UP</a>
    <hr>
    {% endif %}

    {% block content %}
    {% endblock %}
  </div>
  {% bootstrap_javascript %}
</body>
</html>